#!/bin/bash

cd CalcUI/

if [ ! -f Makefile ]; then

    ~/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -config release CalcUI.pro \
            INCPATH+=../MathEngine \
            INCPATH+=../.includes \
            LIBS+="-L../MathEngine -lMathEngine -L../.libs_win32/ -lgsl -lgslcblas -lm"

    if [ $? -ne 0 ]; then
        exit 1
    fi
fi

export PATH=$PATH:~/mxe/usr/bin/

make -j10 SUBLIBS="-L../MathEngine -lMathEngine -L../.libs/ -lgsl -lgslcblas -lm" 2> calcui.cerr
if [ $? -ne 0 ]; then
    vi -R calcui.cerr
    exit 1
else
    rm -f calcui.cerr
fi
