#!/bin/bash

cd CalcUI/

if [ ! -f Makefile ]; then
    qmake -config release CalcUI.pro \
            INCPATH+=../MathEngine \
            INCPATH+=../.includes

    if [ $? -ne 0 ]; then
        exit 1
    fi
fi

make -j10 SUBLIBS="-L../.libs/ -lMathEngine -lgsl -lgslcblas -lm" 2> calcui.cerr
if [ $? -ne 0 ]; then
    vi -R calcui.cerr
    exit 1
else
    rm -f calcui.cerr
fi
