#!/bin/bash

cd CalcUI/

if [ ! -f Makefile ]; then
    qmake -makefile CalcUI.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug \
            INCPATH+=../MathEngine \
            INCPATH+=../.includes
fi

make SUBLIBS="-L../MathEngine -lMathEngine -L../.libs/ -lgsl -lgslcblas -lm" 2> calcui.cerr
if [ $? -ne 0 ]; then
    vi -R calcui.cerr
    exit 1
else
    rm -f calcui.cerr
fi
