#!/bin/bash

root_dir=$(pwd)
include_dir="$root_dir/.includes"
libs_dir="$root_dir/.libs"

rm -rf $include_dir
mkdir -p $include_dir
rm -rf $libs_dir
mkdir -p $libs_dir

cd $include_dir

# Install Catch2
wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp -O Catch2


if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Install GNU Scientific Library
    wget ftp://ftp.gnu.org/gnu/gsl/gsl-latest.tar.gz
    tar -xzf gsl-latest.tar.gz
    rm -f gsl-latest.tar.gz
    gsl_dir=$include_dir/$(ls | grep "gsl-")
    cd $gsl_dir
    ./configure && make
    ln -s $gsl_dir/gsl $include_dir/gsl
    ln -s $gsl_dir/.libs/libgsl.so.25.0.0 $libs_dir/libgsl.so.25
    ln -s $gsl_dir/cblas/.libs/libgslcblas.so.0.0.0 $libs_dir/libgslcblas.so.0

    # Install QT5
    sudo apt-get install qt5-default
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Install GNU Scientific Library
    brew install gsl
    ln -s /usr/local/include/gsl/ $include_dir/gsl
    gsl_dir="/usr/local/Cellar/gsl/2.6/lib"
    sudo cp $gsl_dir/libgsl.25.dylib $libs_dir/libgsl.dylib
    sudo cp $gsl_dir/libgslcblas.0.dylib $libs_dir/libgslcblas.dylib

    # Install QT5
    brew install qt5
fi
