#!/bin/bash

root_dir=$(pwd)

rm -rf .libs/
mkdir -p .libs/
rm -rf .includes/
mkdir -p .includes/
cd .includes/
curr_dir="$root_dir/.includes"

# Install GNU Scientific Library
wget ftp://ftp.gnu.org/gnu/gsl/gsl-latest.tar.gz
tar -xzf gsl-latest.tar.gz
rm -f gsl-latest.tar.gz
gsl_dir=$curr_dir/$(ls | grep "gsl-")
cd $gsl_dir
./configure && make
ln -s $gsl_dir/gsl $curr_dir/gsl
ln -s $gsl_dir/.libs/libgsl.a $root_dir/.libs/libgsl.a
ln -s $gsl_dir/cblas/.libs/libgslcblas.a $root_dir/.libs/libgslcblas.a

# Install QT5
cd $curr_dir
OS=$(uname)
if [ "$OS" == "Linux" ]; then
    wget http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
    chmod +x ./qt-unified-linux-x64-online.run
    ./qt-unified-linux-x64-online.run
elif [ "$OS" == "Darwin" ]; then
    wget http://download.qt.io/official_releases/online_installers/qt-unified-mac-x64-online.dmg
elif [ "$OS" == "WindowsNT" ]; then
    wget http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
fi
