#!/bin/bash

curr_dir=$(pwd)
package_dir=$curr_dir/.package

rm -rf $package_dir
mkdir -p $package_dir
cd $package_dir

CALCULATOR="Calculator"

cp ../CalcUI/CalcUI $CALCULATOR
cp ../.utils/.templates/${CALCULATOR}.sh .

if [ $? -ne 0 ]; then
    exit 1
fi

QT_DIR=/usr/lib/qt5
# cp -r $QT_DIR/plugins/platforms .
# cp -r $QT_DIR/plugins/platformthemes .
# cp /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 $lib_dir/
# cp /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 $lib_dir/

lib_dir=$package_dir/.libs
mkdir $lib_dir

for dependency in $(ldd $CALCULATOR | awk 'NF == 4 {print $3}; NF == 2 {print $1}');
do
    # if echo $dependency | grep -q -e Qt; then
    cp $dependency $lib_dir/
    # fi
done

# for dependency in $(ldd platforms/libqxcb.so | awk 'NF == 4 {print $3}; NF == 2 {print $1}');
# do
#     # if echo $dependency | grep -q -e Qt; then
#     cp $dependency $lib_dir/
#     # fi
# done

if [ $? -ne 0 ]; then
    exit 1
fi

tar -czvf $curr_dir/calcplusplus.tar.gz $CALCULATOR $CALCULATOR.sh .libs/*.so* # platforms/ platformthemes/

cd $curr_dir
cp calcplusplus.tar.gz /media/antonio/HDD-1/VirtualBox/Ubuntu1604/Shared/
