#!/bin/bash

mkdir -p ".package/CalcPlusPlus"

CALCPP=".package/CalcPlusPlus/calcpp"
cp -r UI/calcpp.app .package/CalcPlusPlus/calcpp.app
cp MathEngine/libMathEngine.dylib .package/CalcPlusPlus/calcpp.app/Contents/Resources/

cd .package/

tar -czvf calcplusplus.bottle.tgz CalcPlusPlus/
sha256sum calcplusplus.bottle.tgz
