#!/bin/bash

cd Tests
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../.libs/
elif [[ "$OSTYPE" == "darwin"* ]]; then
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:../.libs/
fi

name=$1

if [[ $name == "nogdb" ]]; then
    ./run
else
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        gdb -q -ex="run" --args run $name
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        lldb -o run run $name
    fi
fi
