#pragma once

#include <string>

#include "../Expressions/Expression.h"

namespace calcpp {

    // returns one of the externally defined function expressions by its name
    expression function(const std::string& name);

    namespace functions {
        // begin sourcegen functions
        extern const expression Beta;
        extern const expression Betainc;
        extern const expression Eig;
        extern const expression LU;
        extern const expression LUsolve;
        extern const expression QR;
        extern const expression SVD;
        extern const expression abs;
        extern const expression absdev;
        extern const expression acos;
        extern const expression acosh;
        extern const expression acot;
        extern const expression acoth;
        extern const expression acsc;
        extern const expression acsch;
        extern const expression argmax;
        extern const expression argmin;
        extern const expression asec;
        extern const expression asech;
        extern const expression asin;
        extern const expression asinh;
        extern const expression atan;
        extern const expression atanh;
        extern const expression bin;
        extern const expression cb;
        extern const expression cbrt;
        extern const expression chisq;
        extern const expression chisq_P;
        extern const expression chisq_Pinv;
        extern const expression chisq_Q;
        extern const expression chisq_Qinv;
        extern const expression chisq_pdf;
        extern const expression choose;
        extern const expression cos;
        extern const expression cosh;
        extern const expression cot;
        extern const expression coth;
        extern const expression csc;
        extern const expression csch;
        extern const expression cubic;
        extern const expression cubicc;
        extern const expression deg;
        extern const expression deriv;
        extern const expression det;
        extern const expression dfact;
        extern const expression diff;
        extern const expression exp;
        extern const expression exp2;
        extern const expression expm1;
        extern const expression exponential;
        extern const expression exponential_P;
        extern const expression exponential_Pinv;
        extern const expression exponential_Q;
        extern const expression exponential_Qinv;
        extern const expression exponential_pdf;
        extern const expression fact;
        extern const expression fcmp;
        extern const expression fft;
        extern const expression frexp;
        extern const expression gamma;
        extern const expression gamma_inc;
        extern const expression gamma_inc_P;
        extern const expression gamma_inc_Q;
        extern const expression gammainv;
        extern const expression gammastar;
        extern const expression gauss_P;
        extern const expression gauss_Pinv;
        extern const expression gauss_Q;
        extern const expression gauss_Qinv;
        extern const expression gauss_pdf;
        extern const expression gcd;
        extern const expression hex;
        extern const expression hypot;
        extern const expression ifft;
        extern const expression integral;
        extern const expression kurtosis;
        extern const expression lag1;
        extern const expression lcm;
        extern const expression ldexp;
        extern const expression ln;
        extern const expression ln1p;
        extern const expression ln2;
        extern const expression lnBeta;
        extern const expression lnchoose;
        extern const expression lndet;
        extern const expression lndfact;
        extern const expression lnfact;
        extern const expression lngamma;
        extern const expression lnpermute;
        extern const expression lnpoch;
        extern const expression log;
        extern const expression log1pm;
        extern const expression logabs;
        extern const expression logn;
        extern const expression max;
        extern const expression mean;
        extern const expression median;
        extern const expression min;
        extern const expression neg;
        extern const expression num;
        extern const expression permute;
        extern const expression poch;
        extern const expression pochrel;
        extern const expression quad;
        extern const expression quadc;
        extern const expression rad;
        extern const expression rand;
        extern const expression randn;
        extern const expression sd;
        extern const expression sec;
        extern const expression sech;
        extern const expression sigmoid;
        extern const expression sin;
        extern const expression sinh;
        extern const expression skew;
        extern const expression sqr;
        extern const expression sqrt;
        extern const expression tan;
        extern const expression tanh;
        extern const expression taylorcoeff;
        extern const expression tss;
        extern const expression var;
        // end sourcegen
    }  // namespace functions

}  // namespace calcpp
